# language: objective-c 
# osx_image: xcode7.2
# xcode_project: ./Demo/MGCollapsibleHeaderDemo.xcodeproj
# xcode_scheme: MGCollapsibleHeader
# xcode_sdk: iphonesimulator9.2
# cache:
# - bundler
# before_install:
# - bundle install
# - cd Demo && pod install

language: objective-c

before_install:

    - pod --version

script:

    - pod lib lint
    - cd Demo
    - pod install
    - xctool -workspace MGCollapsibleHeaderDemo.xcworkspace -scheme 'MGCollapsibleHeaderDemo'